### ISSUE TITLE
Any difference between `Lee filter` and `Speckle filter`?

### ISSUE THREAD

**Issue by apuzzi** [dfguerrerom/sepal_smfm_biota#25]
There are two filter options under Parameters > Optional inputs (SEPAL GUI). Are they the same? If not, how is the speckle filter different from the Lee filter?

**Comment by dfguerrerom** [comment]
@apuzzi thanks for noticing, the lee filter is just a speckle filter, the "speckle filter" button doesn't do anything indeed, so I'll remove it from the gui.
