### ISSUE TITLE
Map coordinates not working properly when placing a point depending on which way you move the map

### ISSUE THREAD

**Issue by apuzzi** [dfguerrerom/sepal_smfm_biota#27]
I noticed that when I place a point in Cambodia going from left to right in the map as opposed to going from right to left, it results in different coordinates (for the same point). The longitude when you toggle to Cambodia from right to left and place a point is negative 200 something (supposed to be 160 something). Not sure if this is a bug or just a limitation of the map ui.

**Comment by dfguerrerom** [comment]
What is happening is that `ipyleaflet` creates a new map view when the map is panned out of the world bounds, it would be easily corrected using the worlCopyJump attribute to the map.
