### ISSUE TITLE
Tile option

### ISSUE THREAD

**Issue by apuzzi** [dfguerrerom/sepal_smfm_biota#28]
Not sure what the large tile option under required inputs refers to. Is it the same as selecting the 5x5 tile option? what happens if I choose 1x1 tile size and leave the large tile option selected? Also, is window size (default value 5) under optional inputs the same as 5x5 tile size? If I leave window size = 5 will it affect my tile size 1x1 in required inputs?
![image](https://user-images.githubusercontent.com/35314996/122093974-fbc10a00-cde1-11eb-9185-5cf4df80999f.png)
![image](https://user-images.githubusercontent.com/35314996/122093924-f1067500-cde1-11eb-9c00-1613ac5c4ea6.png)

**Comment by dfguerrerom** [comment]
@apuzzi, thanks for noticing it. We have removed the large tile checkbox and provided more info about the optional parameters in the module.
The window size refers to the lee filter window, is not related with the size of the tile.

**Comment by apuzzi** [comment]
Thank you @dfguerrerom !
